/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "strings.h"

bool_t
xdr_networkMessage(XDR *xdrs, networkMessage *objp)
{

	if (!xdr_string(xdrs, &objp->name, 64))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->val))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->seqnum))
		return (FALSE);
	if (!xdr_pointer(xdrs, (char **)&objp->payload, sizeof(u_int), (xdrproc_t)xdr_u_int))
		return (FALSE);
	return (TRUE);
}
