/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRINGS_H_RPCGEN
#define _STRINGS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct networkMessage {
	char *name;
	int val;
	u_int seqnum;
	u_int *payload;
};
typedef struct networkMessage networkMessage;
#ifdef __cplusplus
extern "C" bool_t xdr_networkMessage(XDR *, networkMessage*);
#elif __STDC__
extern  bool_t xdr_networkMessage(XDR *, networkMessage*);
#else /* Old Style C */
bool_t xdr_networkMessage();
#endif /* Old Style C */


#define CRACKER_PROG ((rpc_uint)0x33381138)
#define CRACKER_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define send_message ((rpc_uint)1)
extern "C" char ** send_message_1(networkMessage *, CLIENT *);
extern "C" char ** send_message_1_svc(networkMessage *, struct svc_req *);

#elif __STDC__
#define send_message ((rpc_uint)1)
extern  char ** send_message_1(networkMessage *, CLIENT *);
extern  char ** send_message_1_svc(networkMessage *, struct svc_req *);

#else /* Old Style C */
#define send_message ((rpc_uint)1)
extern  char ** send_message_1();
extern  char ** send_message_1_svc();
#endif /* Old Style C */

#endif /* !_STRINGS_H_RPCGEN */
