/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cracker.h"

bool_t
xdr_crackMessage(XDR *xdrs, crackMessage *objp)
{

	if (!xdr_pointer(xdrs, (char **)&objp->hash, sizeof(uint8_t), (xdrproc_t)xdr_uint8_t))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->len))
		return (FALSE);
	return (TRUE);
}
