/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cracker.h"

char **
crack_password_1_svc(crackMessage *argp, struct svc_req *rqstp)
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}

char **
inform_available_1_svc(void *argp, struct svc_req *rqstp)
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}

void *
deliver_result_1_svc(char **argp, struct svc_req *rqstp)
{

	static char* result;

	/*
	 * insert server code here
	 */

	return((void*) &result);
}
