/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CRACKER_H_RPCGEN
#define _CRACKER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct crackMessage {
	uint8_t *hash;
	int len;
};
typedef struct crackMessage crackMessage;
#ifdef __cplusplus
extern "C" bool_t xdr_crackMessage(XDR *, crackMessage*);
#elif __STDC__
extern  bool_t xdr_crackMessage(XDR *, crackMessage*);
#else /* Old Style C */
bool_t xdr_crackMessage();
#endif /* Old Style C */


#define cracker ((rpc_uint)0x20000099)
#define 0 ((rpc_uint)1)

#ifdef __cplusplus
#define crack_password ((rpc_uint)1)
extern "C" char ** crack_password_1(crackMessage *, CLIENT *);
extern "C" char ** crack_password_1_svc(crackMessage *, struct svc_req *);
#define inform_available ((rpc_uint)2)
extern "C" char ** inform_available_1(void *, CLIENT *);
extern "C" char ** inform_available_1_svc(void *, struct svc_req *);
#define deliver_result ((rpc_uint)3)
extern "C" void * deliver_result_1(char **, CLIENT *);
extern "C" void * deliver_result_1_svc(char **, struct svc_req *);

#elif __STDC__
#define crack_password ((rpc_uint)1)
extern  char ** crack_password_1(crackMessage *, CLIENT *);
extern  char ** crack_password_1_svc(crackMessage *, struct svc_req *);
#define inform_available ((rpc_uint)2)
extern  char ** inform_available_1(void *, CLIENT *);
extern  char ** inform_available_1_svc(void *, struct svc_req *);
#define deliver_result ((rpc_uint)3)
extern  void * deliver_result_1(char **, CLIENT *);
extern  void * deliver_result_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define crack_password ((rpc_uint)1)
extern  char ** crack_password_1();
extern  char ** crack_password_1_svc();
#define inform_available ((rpc_uint)2)
extern  char ** inform_available_1();
extern  char ** inform_available_1_svc();
#define deliver_result ((rpc_uint)3)
extern  void * deliver_result_1();
extern  void * deliver_result_1_svc();
#endif /* Old Style C */

#endif /* !_CRACKER_H_RPCGEN */
