/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cracker.h"

networkMessage *
send_message_1_svc(networkMessage *argp, struct svc_req *rqstp)
{
	static networkMessage  result;

	/*
	 * insert server code here
	 */

	return &result;
}
