/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CRACKER_H_RPCGEN
#define _CRACKER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct networkMessage {
	int connid;
	int seqnum;
	char *payload;
};
typedef struct networkMessage networkMessage;
#ifdef __cplusplus
extern "C" bool_t xdr_networkMessage(XDR *, networkMessage*);
#elif __STDC__
extern  bool_t xdr_networkMessage(XDR *, networkMessage*);
#else /* Old Style C */
bool_t xdr_networkMessage();
#endif /* Old Style C */


#define CRACKER_PROG ((rpc_uint)0x33301138)
#define CRACKER_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define SEND_MESSAGE ((rpc_uint)1)
extern "C" networkMessage * send_message_1(networkMessage *, CLIENT *);
extern "C" networkMessage * send_message_1_svc(networkMessage *, struct svc_req *);

#elif __STDC__
#define SEND_MESSAGE ((rpc_uint)1)
extern  networkMessage * send_message_1(networkMessage *, CLIENT *);
extern  networkMessage * send_message_1_svc(networkMessage *, struct svc_req *);

#else /* Old Style C */
#define SEND_MESSAGE ((rpc_uint)1)
extern  networkMessage * send_message_1();
extern  networkMessage * send_message_1_svc();
#endif /* Old Style C */

#endif /* !_CRACKER_H_RPCGEN */
