// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lspmessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lspmessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* LSPMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LSPMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lspmessage_2eproto() {
  protobuf_AddDesc_lspmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lspmessage.proto");
  GOOGLE_CHECK(file != NULL);
  LSPMessage_descriptor_ = file->message_type(0);
  static const int LSPMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LSPMessage, connid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LSPMessage, seqnum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LSPMessage, payload_),
  };
  LSPMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LSPMessage_descriptor_,
      LSPMessage::default_instance_,
      LSPMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LSPMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LSPMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LSPMessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lspmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LSPMessage_descriptor_, &LSPMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lspmessage_2eproto() {
  delete LSPMessage::default_instance_;
  delete LSPMessage_reflection_;
}

void protobuf_AddDesc_lspmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020lspmessage.proto\"=\n\nLSPMessage\022\016\n\006conn"
    "id\030\001 \002(\r\022\016\n\006seqnum\030\002 \002(\r\022\017\n\007payload\030\003 \002("
    "\014", 81);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lspmessage.proto", &protobuf_RegisterTypes);
  LSPMessage::default_instance_ = new LSPMessage();
  LSPMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lspmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lspmessage_2eproto {
  StaticDescriptorInitializer_lspmessage_2eproto() {
    protobuf_AddDesc_lspmessage_2eproto();
  }
} static_descriptor_initializer_lspmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int LSPMessage::kConnidFieldNumber;
const int LSPMessage::kSeqnumFieldNumber;
const int LSPMessage::kPayloadFieldNumber;
#endif  // !_MSC_VER

LSPMessage::LSPMessage()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LSPMessage::InitAsDefaultInstance() {
}

LSPMessage::LSPMessage(const LSPMessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LSPMessage::SharedCtor() {
  _cached_size_ = 0;
  connid_ = 0u;
  seqnum_ = 0u;
  payload_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LSPMessage::~LSPMessage() {
  SharedDtor();
}

void LSPMessage::SharedDtor() {
  if (payload_ != &::google::protobuf::internal::kEmptyString) {
    delete payload_;
  }
  if (this != default_instance_) {
  }
}

void LSPMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LSPMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LSPMessage_descriptor_;
}

const LSPMessage& LSPMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lspmessage_2eproto();
  return *default_instance_;
}

LSPMessage* LSPMessage::default_instance_ = NULL;

LSPMessage* LSPMessage::New() const {
  return new LSPMessage;
}

void LSPMessage::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    connid_ = 0u;
    seqnum_ = 0u;
    if (has_payload()) {
      if (payload_ != &::google::protobuf::internal::kEmptyString) {
        payload_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool LSPMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 connid = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &connid_)));
          set_has_connid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_seqnum;
        break;
      }

      // required uint32 seqnum = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_seqnum:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seqnum_)));
          set_has_seqnum();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_payload;
        break;
      }

      // required bytes payload = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void LSPMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 connid = 1;
  if (has_connid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->connid(), output);
  }

  // required uint32 seqnum = 2;
  if (has_seqnum()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->seqnum(), output);
  }

  // required bytes payload = 3;
  if (has_payload()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      3, this->payload(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* LSPMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 connid = 1;
  if (has_connid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->connid(), target);
  }

  // required uint32 seqnum = 2;
  if (has_seqnum()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->seqnum(), target);
  }

  // required bytes payload = 3;
  if (has_payload()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->payload(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int LSPMessage::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 connid = 1;
    if (has_connid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->connid());
    }

    // required uint32 seqnum = 2;
    if (has_seqnum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->seqnum());
    }

    // required bytes payload = 3;
    if (has_payload()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->payload());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LSPMessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const LSPMessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const LSPMessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void LSPMessage::MergeFrom(const LSPMessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_connid()) {
      set_connid(from.connid());
    }
    if (from.has_seqnum()) {
      set_seqnum(from.seqnum());
    }
    if (from.has_payload()) {
      set_payload(from.payload());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void LSPMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LSPMessage::CopyFrom(const LSPMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LSPMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void LSPMessage::Swap(LSPMessage* other) {
  if (other != this) {
    std::swap(connid_, other->connid_);
    std::swap(seqnum_, other->seqnum_);
    std::swap(payload_, other->payload_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata LSPMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LSPMessage_descriptor_;
  metadata.reflection = LSPMessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
