CFLAGS = -g -DRPC_SVC_FG

all: client server

client: cracker_client.o cracker_clnt.o cracker_xdr.o
	$(CC) -o client cracker_client.o cracker_clnt.o cracker_xdr.o

server: cracker_server.o cracker_svc.o  cracker_xdr.o
	g++ -o server cracker_server.o cracker_svc.o cracker_xdr.o

cracker_svc.o: cracker.h
	$(CC) $(CFLAGS) -c cracker_svc.c

cracker_clnt.o: cracker.h
	$(CC) $(CFLAGS) -c cracker_clnt.c

cracker_xdr.o: cracker_xdr.c 
	$(CC) $(CFLAGS) -c cracker_xdr.c

cracker_server.o: cracker_server.c cracker.h
	g++ $(CFLAGS) -c cracker_server.c

cracker_client.o: cracker_client.c cracker.h
	$(CC) $(CFLAGS) -c cracker_client.c

cracker.h: cracker.x
	rpcgen -a -C cracker.x

clean:
	rm -f client cracker_client.o server cracker_server.o cracker_xdr.* cracker_clnt.* cracker_svc.* cracker.h cracker_client.c cracker_server.c
