/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct stuff {
	char *name;
	int val;
};
typedef struct stuff stuff;
#ifdef __cplusplus
extern "C" bool_t xdr_stuff(XDR *, stuff*);
#elif __STDC__
extern  bool_t xdr_stuff(XDR *, stuff*);
#else /* Old Style C */
bool_t xdr_stuff();
#endif /* Old Style C */


#define NFS_PROGRM ((rpc_uint)0x33348688)
#define NFS_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define TEST_FUNC ((rpc_uint)1)
extern "C" char ** test_func_1(stuff *, CLIENT *);
extern "C" char ** test_func_1_svc(stuff *, struct svc_req *);
#define callbackfn ((rpc_uint)2)
extern "C" void * callbackfn_1(int *, CLIENT *);
extern "C" void * callbackfn_1_svc(int *, struct svc_req *);

#elif __STDC__
#define TEST_FUNC ((rpc_uint)1)
extern  char ** test_func_1(stuff *, CLIENT *);
extern  char ** test_func_1_svc(stuff *, struct svc_req *);
#define callbackfn ((rpc_uint)2)
extern  void * callbackfn_1(int *, CLIENT *);
extern  void * callbackfn_1_svc(int *, struct svc_req *);

#else /* Old Style C */
#define TEST_FUNC ((rpc_uint)1)
extern  char ** test_func_1();
extern  char ** test_func_1_svc();
#define callbackfn ((rpc_uint)2)
extern  void * callbackfn_1();
extern  void * callbackfn_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_H_RPCGEN */
